services:
  db:
    image: mysql:8.0
    container_name: mysql_startdoor
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    restart: always
    environment:
      MYSQL_DATABASE: startdoor
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    depends_on:
      - app