export const DROPDOWN_VALUES_CONST = {
  PAIS_ORIGEM: [
    { label: 'Selecione...', value: '' },
    { label: 'Afeganistão', value: 'Afeganistão' },
    { label: 'África do Sul', value: 'África do Sul' },
    { label: 'Albânia', value: 'Albânia' },
    { label: 'Alemanha', value: 'Alemanha' },
    { label: 'Andorra', value: 'Andorra' },
    { label: 'Angola', value: 'Angola' },
    { label: 'Antígua e Barbuda', value: 'Antígua e Barbuda' },
    { label: 'Arábia Saudita', value: 'Arábia Saudita' },
    { label: 'Argélia', value: 'Argélia' },
    { label: 'Argentina', value: 'Argentina' },
    { label: 'Armênia', value: 'Armênia' },
    { label: 'Austrália', value: 'Austrália' },
    { label: 'Áustria', value: 'Áustria' },
    { label: 'Azerbaijão', value: 'Azerbaijão' },
    { label: 'Bahamas', value: 'Bahamas' },
    { label: 'Bangladesh', value: 'Bangladesh' },
    { label: 'Barbados', value: 'Barbados' },
    { label: 'Bélgica', value: 'Bélgica' },
    { label: 'Belize', value: 'Belize' },
    { label: 'Benin', value: 'Benin' },
    { label: 'Bielorrússia', value: 'Bielorrússia' },
    { label: 'Bolívia', value: 'Bolívia' },
    { label: 'Bósnia e Herzegovina', value: 'Bósnia e Herzegovina' },
    { label: 'Botsuana', value: 'Botsuana' },
    { label: 'Brasil', value: 'Brasil' },
    { label: 'Brunei', value: 'Brunei' },
    { label: 'Bulgária', value: 'Bulgária' },
    { label: 'Burkina Faso', value: 'Burkina Faso' },
    { label: 'Burundi', value: 'Burundi' },
    { label: 'Butão', value: 'Butão' },
    { label: 'Cabo Verde', value: 'Cabo Verde' },
    { label: 'Camarões', value: 'Camarões' },
    { label: 'Canadá', value: 'Canadá' },
    { label: 'Catar', value: 'Catar' },
    { label: 'Chade', value: 'Chade' },
    { label: 'Chile', value: 'Chile' },
    { label: 'China', value: 'China' },
    { label: 'Chipre', value: 'Chipre' },
    { label: 'Colômbia', value: 'Colômbia' },
    { label: 'Comores', value: 'Comores' },
    { label: 'Congo', value: 'Congo' },
    { label: 'Coreia do Norte', value: 'Coreia do Norte' },
    { label: 'Coreia do Sul', value: 'Coreia do Sul' },
    { label: 'Costa do Marfim', value: 'Costa do Marfim' },
    { label: 'Costa Rica', value: 'Costa Rica' },
    { label: 'Croácia', value: 'Croácia' },
    { label: 'Cuba', value: 'Cuba' },
    { label: 'Dinamarca', value: 'Dinamarca' },
    { label: 'Djibuti', value: 'Djibuti' },
    { label: 'Dominica', value: 'Dominica' },
    { label: 'Egito', value: 'Egito' },
    { label: 'El Salvador', value: 'El Salvador' },
    { label: 'Emirados Árabes Unidos', value: 'Emirados Árabes Unidos' },
    { label: 'Equador', value: 'Equador' },
    { label: 'Eritreia', value: 'Eritreia' },
    { label: 'Eslováquia', value: 'Eslováquia' },
    { label: 'Eslovênia', value: 'Eslovênia' },
    { label: 'Espanha', value: 'Espanha' },
    { label: 'Estados Unidos', value: 'Estados Unidos' },
    { label: 'Estônia', value: 'Estônia' },
    { label: 'Etiópia', value: 'Etiópia' },
    { label: 'Fiji', value: 'Fiji' },
    { label: 'Filipinas', value: 'Filipinas' },
    { label: 'Finlândia', value: 'Finlândia' },
    { label: 'França', value: 'França' },
    { label: 'Gabão', value: 'Gabão' },
    { label: 'Gâmbia', value: 'Gâmbia' },
    { label: 'Gana', value: 'Gana' },
    { label: 'Geórgia', value: 'Geórgia' },
    { label: 'Granada', value: 'Granada' },
    { label: 'Grécia', value: 'Grécia' },
    { label: 'Guatemala', value: 'Guatemala' },
    { label: 'Guiana', value: 'Guiana' },
    { label: 'Guiné', value: 'Guiné' },
    { label: 'Guiné-Bissau', value: 'Guiné-Bissau' },
    { label: 'Haiti', value: 'Haiti' },
    { label: 'Holanda', value: 'Holanda' },
    { label: 'Honduras', value: 'Honduras' },
    { label: 'Hungria', value: 'Hungria' },
    { label: 'Iêmen', value: 'Iêmen' },
    { label: 'Índia', value: 'Índia' },
    { label: 'Indonésia', value: 'Indonésia' },
    { label: 'Irã', value: 'Irã' },
    { label: 'Iraque', value: 'Iraque' },
    { label: 'Irlanda', value: 'Irlanda' },
    { label: 'Islândia', value: 'Islândia' },
    { label: 'Israel', value: 'Israel' },
    { label: 'Itália', value: 'Itália' },
    { label: 'Jamaica', value: 'Jamaica' },
    { label: 'Japão', value: 'Japão' },
    { label: 'Jordânia', value: 'Jordânia' },
    { label: 'Cazaquistão', value: 'Cazaquistão' },
    { label: 'Quênia', value: 'Quênia' },
    { label: 'Kiribati', value: 'Kiribati' },
    { label: 'Kuwait', value: 'Kuwait' },
    { label: 'Laos', value: 'Laos' },
    { label: 'Lesoto', value: 'Lesoto' },
    { label: 'Letônia', value: 'Letônia' },
    { label: 'Líbano', value: 'Líbano' },
    { label: 'Libéria', value: 'Libéria' },
    { label: 'Líbia', value: 'Líbia' },
    { label: 'Liechtenstein', value: 'Liechtenstein' },
    { label: 'Lituânia', value: 'Lituânia' },
    { label: 'Luxemburgo', value: 'Luxemburgo' },
    { label: 'Madagascar', value: 'Madagascar' },
    { label: 'Malásia', value: 'Malásia' },
    { label: 'Malaui', value: 'Malaui' },
    { label: 'Maldivas', value: 'Maldivas' },
    { label: 'Mali', value: 'Mali' },
    { label: 'Malta', value: 'Malta' },
    { label: 'Marrocos', value: 'Marrocos' },
    { label: 'Mauritânia', value: 'Mauritânia' },
    { label: 'Maurício', value: 'Maurício' },
    { label: 'México', value: 'México' },
    { label: 'Mianmar', value: 'Mianmar' },
    { label: 'Micronésia', value: 'Micronésia' },
    { label: 'Moçambique', value: 'Moçambique' },
    { label: 'Moldávia', value: 'Moldávia' },
    { label: 'Mônaco', value: 'Mônaco' },
    { label: 'Mongólia', value: 'Mongólia' },
    { label: 'Namíbia', value: 'Namíbia' },
    { label: 'Nauru', value: 'Nauru' },
    { label: 'Nepal', value: 'Nepal' },
    { label: 'Nicarágua', value: 'Nicarágua' },
    { label: 'Níger', value: 'Níger' },
    { label: 'Nigéria', value: 'Nigéria' },
    { label: 'Noruega', value: 'Noruega' },
    { label: 'Nova Zelândia', value: 'Nova Zelândia' },
    { label: 'Omã', value: 'Omã' },
    { label: 'Paquistão', value: 'Paquistão' },
    { label: 'Palau', value: 'Palau' },
    { label: 'Panamá', value: 'Panamá' },
    { label: 'Papua-Nova Guiné', value: 'Papua-Nova Guiné' },
    { label: 'Paraguai', value: 'Paraguai' },
    { label: 'Peru', value: 'Peru' },
    { label: 'Polônia', value: 'Polônia' },
    { label: 'Portugal', value: 'Portugal' },
    { label: 'Quirguistão', value: 'Quirguistão' },
    { label: 'Reino Unido', value: 'Reino Unido' },
    { label: 'República Centro-Africana', value: 'República Centro-Africana' },
    { label: 'República Checa', value: 'República Checa' },
    {
      label: 'República Democrática do Congo',
      value: 'República Democrática do Congo',
    },
    { label: 'República Dominicana', value: 'República Dominicana' },
    { label: 'Romênia', value: 'Romênia' },
    { label: 'Ruanda', value: 'Ruanda' },
    { label: 'Rússia', value: 'Rússia' },
    { label: 'Salvador', value: 'Salvador' },
    { label: 'Samoa', value: 'Samoa' },
    { label: 'San Marino', value: 'San Marino' },
    { label: 'Santa Lúcia', value: 'Santa Lúcia' },
    { label: 'São Cristóvão e Nevis', value: 'São Cristóvão e Nevis' },
    { label: 'São Tomé e Príncipe', value: 'São Tomé e Príncipe' },
    { label: 'São Vicente e Granadinas', value: 'São Vicente e Granadinas' },
    { label: 'Senegal', value: 'Senegal' },
    { label: 'Serra Leoa', value: 'Serra Leoa' },
    { label: 'Sérvia', value: 'Sérvia' },
    { label: 'Síria', value: 'Síria' },
    { label: 'Singapura', value: 'Singapura' },
    { label: 'Somália', value: 'Somália' },
    { label: 'Sri Lanka', value: 'Sri Lanka' },
    { label: 'Suazilândia', value: 'Suazilândia' },
    { label: 'Sudão', value: 'Sudão' },
    { label: 'Sudão do Sul', value: 'Sudão do Sul' },
    { label: 'Suécia', value: 'Suécia' },
    { label: 'Suíça', value: 'Suíça' },
    { label: 'Suriname', value: 'Suriname' },
    { label: 'Tailândia', value: 'Tailândia' },
    { label: 'Taiwan', value: 'Taiwan' },
    { label: 'Tajiquistão', value: 'Tajiquistão' },
    { label: 'Tanzânia', value: 'Tanzânia' },
    { label: 'Tcheca', value: 'Tcheca' },
    { label: 'Togo', value: 'Togo' },
    { label: 'Tonga', value: 'Tonga' },
    { label: 'Trinidad e Tobago', value: 'Trinidad e Tobago' },
    { label: 'Tunísia', value: 'Tunísia' },
    { label: 'Turquia', value: 'Turquia' },
    { label: 'Turcomenistão', value: 'Turcomenistão' },
    { label: 'Tuvalu', value: 'Tuvalu' },
    { label: 'Ucrânia', value: 'Ucrânia' },
    { label: 'Uganda', value: 'Uganda' },
    { label: 'Uruguai', value: 'Uruguai' },
    { label: 'Uzbequistão', value: 'Uzbequistão' },
    { label: 'Vanuatu', value: 'Vanuatu' },
    { label: 'Vaticano', value: 'Vaticano' },
    { label: 'Venezuela', value: 'Venezuela' },
    { label: 'Vietnã', value: 'Vietnã' },
    { label: 'Zâmbia', value: 'Zâmbia' },
    { label: 'Zimbábue', value: 'Zimbábue' },
  ] as const,

  MODELO_TRABALHO: [
    { label: 'Selecione...', value: '' },
    { label: 'Presencial', value: 'Presencial' },
    { label: 'Hibrido', value: 'Hibrido' },
    { label: 'Remoto', value: 'Remoto' },
  ] as const,

  ESTADO_ATUACAO: [
    { label: 'Selecione...', value: '' },
    { label: 'Acre', value: 'Acre' },
    { label: 'Alagoas', value: 'Alagoas' },
    { label: 'Amapá', value: 'Amapá' },
    { label: 'Amazonas', value: 'Amazonas' },
    { label: 'Bahia', value: 'Bahia' },
    { label: 'Ceará', value: 'Ceará' },
    { label: 'Distrito Federal', value: 'Distrito Federal' },
    { label: 'Espírito Santo', value: 'Espírito Santo' },
    { label: 'Goiás', value: 'Goiás' },
    { label: 'Maranhão', value: 'Maranhão' },
    { label: 'Mato Grosso', value: 'Mato Grosso' },
    { label: 'Mato Grosso do Sul', value: 'Mato Grosso do Sul' },
    { label: 'Minas Gerais', value: 'Minas Gerais' },
    { label: 'Pará', value: 'Pará' },
    { label: 'Paraíba', value: 'Paraíba' },
    { label: 'Paraná', value: 'Paraná' },
    { label: 'Pernambuco', value: 'Pernambuco' },
    { label: 'Piauí', value: 'Piauí' },
    { label: 'Rio de Janeiro', value: 'Rio de Janeiro' },
    { label: 'Rio Grande do Norte', value: 'Rio Grande do Norte' },
    { label: 'Rio Grande do Sul', value: 'Rio Grande do Sul' },
    { label: 'Rondônia', value: 'Rondônia' },
    { label: 'Roraima', value: 'Roraima' },
    { label: 'Santa Catarina', value: 'Santa Catarina' },
    { label: 'São Paulo', value: 'São Paulo' },
    { label: 'Sergipe', value: 'Sergipe' },
    { label: 'Tocantins', value: 'Tocantins' },
  ] as const,

  SETOR_INTERESSE: [
    { label: 'Selecione...', value: '' },
    { label: 'Tecnologia da Informação', value: 'Tecnologia da Informação' },
    {
      label: 'Desenvolvimento de Software',
      value: 'Desenvolvimento de Software',
    },
    { label: 'Engenharia de Software', value: 'Engenharia de Software' },
    { label: 'Ciência de Dados', value: 'Ciência de Dados' },
    { label: 'Inteligência Artificial', value: 'Inteligência Artificial' },
    { label: 'Segurança da Informação', value: 'Segurança da Informação' },
    { label: 'Infraestrutura e Redes', value: 'Infraestrutura e Redes' },
    { label: 'Computação em Nuvem', value: 'Computação em Nuvem' },
    { label: 'UX/UI Design', value: 'UX/UI Design' },
    { label: 'Design Gráfico', value: 'Design Gráfico' },
    { label: 'Produto Digital', value: 'Produto Digital' },
    { label: 'Gestão de Produtos', value: 'Gestão de Produtos' },
    { label: 'Gestão de Projetos', value: 'Gestão de Projetos' },
    { label: 'Administração', value: 'Administração' },
    { label: 'Financeiro', value: 'Financeiro' },
    { label: 'Contabilidade', value: 'Contabilidade' },
    { label: 'Auditoria', value: 'Auditoria' },
    { label: 'Economia', value: 'Economia' },
    { label: 'Marketing', value: 'Marketing' },
    { label: 'Marketing Digital', value: 'Marketing Digital' },
    { label: 'Vendas', value: 'Vendas' },
    { label: 'Customer Success', value: 'Customer Success' },
    { label: 'Atendimento ao Cliente', value: 'Atendimento ao Cliente' },
    { label: 'Recursos Humanos', value: 'Recursos Humanos' },
    { label: 'Recrutamento e Seleção', value: 'Recrutamento e Seleção' },
    {
      label: 'Treinamento e Desenvolvimento',
      value: 'Treinamento e Desenvolvimento',
    },
    { label: 'Logística', value: 'Logística' },
    { label: 'Supply Chain', value: 'Supply Chain' },
    { label: 'Compras e Suprimentos', value: 'Compras e Suprimentos' },
    { label: 'Jurídico', value: 'Jurídico' },
    { label: 'Compliance', value: 'Compliance' },
    { label: 'Educação', value: 'Educação' },
    {
      label: 'Pesquisa e Desenvolvimento',
      value: 'Pesquisa e Desenvolvimento',
    },
    { label: 'Engenharia', value: 'Engenharia' },
    { label: 'Arquitetura', value: 'Arquitetura' },
    { label: 'Saúde', value: 'Saúde' },
    { label: 'Biotecnologia', value: 'Biotecnologia' },
    { label: 'Agronegócio', value: 'Agronegócio' },
    { label: 'Sustentabilidade', value: 'Sustentabilidade' },
    { label: 'Relações Internacionais', value: 'Relações Internacionais' },
  ] as const,

  RECEITA_ANUAL: [
    { label: 'Selecione...', value: '' },
    { label: 'R$1 milhão', value: 'R$1 milhão' },
    { label: 'R$10 milhões', value: 'R$10 milhões' },
    { label: 'R$50 milhões', value: 'R$50 milhões' },
    { label: 'R$100 milhões', value: 'R$100 milhões' },
    { label: 'R$500 milhões', value: 'R$500 milhões' },
    { label: 'R$1 bilhão', value: 'R$1 bilhão' },
    { label: 'R$10 bilhões', value: 'R$10 bilhões' },
    { label: 'R$50 bilhões', value: 'R$50 bilhões' },
    { label: 'R$100 bilhões', value: 'R$100 bilhões' },
    { label: 'R$250 bilhões', value: 'R$250 bilhões' },
    { label: 'R$500 bilhões', value: 'R$500 bilhões' },
    { label: '+R$500 bilhões', value: '+R$500 bilhões' },
  ] as const,

  TAMANHO_EMPRESA: [
    { label: 'Selecione...', value: '' },
    { label: '1-10', value: '1-10' },
    { label: '11-50', value: '11-50' },
    { label: '51-100', value: '51-100' },
    { label: '101-250', value: '101-250' },
    { label: '251-500', value: '251-500' },
    { label: '501-1000', value: '501-1000' },
    { label: '1001-5000', value: '1001-5000' },
    { label: '5001-10000', value: '5001-10000' },
    { label: '10001-50000', value: '10001-50000' },
    { label: '50001-100000', value: '50001-100000' },
    { label: '+100000', value: '+100000' },
  ] as const,

  NOTA_CONDI: [
    { label: 'Selecione...', value: '' },
    { label: '1', value: 1 },
    { label: '2', value: 2 },
    { label: '3', value: 3 },
    { label: '4', value: 4 },
    { label: '5', value: 5 },
  ],
};
