-- 1. LIMPEZA TOTAL (Respeitando as restrições de chave estrangeira)
DELETE FROM empresa_setor;
DELETE FROM estudante_avaliacao;
DELETE FROM empresa;
DELETE FROM empresa_media;
DELETE FROM estudante;

-- 2. SETORES (IDs fixos para o DataLoader não recriar)
INSERT INTO setor (id, nome, created_at) VALUES (1, 'Administrativo', NOW());
INSERT INTO setor (id, nome, created_at) VALUES (2, 'Comercial', NOW());
INSERT INTO setor (id, nome, created_at) VALUES (3, 'Engenharia', NOW());
INSERT INTO setor (id, nome, created_at) VALUES (4, 'Financeiro', NOW());
INSERT INTO setor (id, nome, created_at) VALUES (5, 'Jurídico', NOW());
INSERT INTO setor (id, nome, created_at) VALUES (6, 'Marketing', NOW());
INSERT INTO setor (id, nome, created_at) VALUES (7, 'Recursos Humanos', NOW());
INSERT INTO setor (id, nome, created_at) VALUES (8, 'Tecnologia da Informação', NOW());
INSERT INTO setor (id, nome, created_at) VALUES (9, 'Outro', NOW());

-- 3. ESTUDANTES
INSERT INTO estudante (id, uuid, nome, `user`, email, senha, created_at) VALUES (1, 'user-gus', 'Gustavo Silva', 'guss_dev', 'gus@teste.com', '123', NOW());
INSERT INTO estudante (id, uuid, nome, `user`, email, senha, created_at) VALUES (2, 'user-ana', 'Ana Silva', 'ana_tech', 'ana@teste.com', '123', NOW());
INSERT INTO estudante (id, uuid, nome, `user`, email, senha, created_at) VALUES (5, 'user-diego', 'Diego Oliveira', 'diego_dev', 'diego@teste.com', '123', NOW());
INSERT INTO estudante (id, uuid, nome, `user`, email, senha, created_at) VALUES (6, 'user-fernanda', 'Fernanda Lima', 'fer_qa', 'fer@teste.com', '123', NOW());
INSERT INTO estudante (id, uuid, nome, `user`, email, senha, created_at) VALUES (7, 'user-gabriel', 'Gabriel Santos', 'gabs_data', 'gabriel@teste.com', '123', NOW());

-- 4. MÉDIAS DAS EMPRESAS
INSERT INTO empresa_media (id, media_ambiente, media_aprendizado, media_beneficios, media_cultura, media_efetivacao, media_entrevista, media_feedback, media_infraestrutura, media_integracao, media_remuneracao, media_rotina, media_lideranca, media_geral, salario_min_piso, salario_max_teto, salario_base_medio, created_at) VALUES (1, 4.50, 5.00, 4.20, 4.80, 4.00, 4.50, 4.30, 4.70, 4.60, 4.10, 4.40, 4.50, 4.47, 3000.00, 7500.00, 5250.00, NOW());
INSERT INTO empresa_media (id, media_ambiente, media_aprendizado, media_beneficios, media_cultura, media_efetivacao, media_entrevista, media_feedback, media_infraestrutura, media_integracao, media_remuneracao, media_rotina, media_lideranca, media_geral, salario_min_piso, salario_max_teto, salario_base_medio, created_at) VALUES (7, 5.00, 5.00, 5.00, 5.00, 5.00, 5.00, 5.00, 5.00, 5.00, 5.00, 5.00, 5.00, 5.00, 10000.00, 18000.00, 14000.00, NOW());
INSERT INTO empresa_media (id, media_ambiente, media_aprendizado, media_beneficios, media_cultura, media_efetivacao, media_entrevista, media_feedback, media_infraestrutura, media_integracao, media_remuneracao, media_rotina, media_lideranca, media_geral, salario_min_piso, salario_max_teto, salario_base_medio, created_at) VALUES (8, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1500.00, 3000.00, 2250.00, NOW());
INSERT INTO empresa_media (id, media_ambiente, media_aprendizado, media_beneficios, media_cultura, media_efetivacao, media_entrevista, media_feedback, media_infraestrutura, media_integracao, media_remuneracao, media_rotina, media_lideranca, media_geral, salario_min_piso, salario_max_teto, salario_base_medio, created_at) VALUES (11, 4.20, 4.50, 4.00, 4.60, 4.30, 4.10, 4.00, 4.40, 4.50, 3.90, 3.80, 4.20, 4.21, 2800.00, 6000.00, 4400.00, NOW());
INSERT INTO empresa_media (id, media_ambiente, media_aprendizado, media_beneficios, media_cultura, media_efetivacao, media_entrevista, media_feedback, media_infraestrutura, media_integracao, media_remuneracao, media_rotina, media_lideranca, media_geral, salario_min_piso, salario_max_teto, salario_base_medio, created_at) VALUES (12, 3.50, 4.80, 4.90, 3.00, 4.50, 4.20, 3.50, 4.90, 3.80, 5.00, 1.50, 3.00, 3.88, 5000.00, 13000.00, 9000.00, NOW());
INSERT INTO empresa_media (id, media_ambiente, media_aprendizado, media_beneficios, media_cultura, media_efetivacao, media_entrevista, media_feedback, media_infraestrutura, media_integracao, media_remuneracao, media_rotina, media_lideranca, media_geral, salario_min_piso, salario_max_teto, salario_base_medio, created_at) VALUES (14, 4.90, 5.00, 2.00, 5.00, 3.00, 4.80, 4.90, 3.50, 5.00, 2.50, 4.50, 4.80, 4.16, 4000.00, 9000.00, 6500.00, NOW());
INSERT INTO empresa_media (id, media_ambiente, media_aprendizado, media_beneficios, media_cultura, media_efetivacao, media_entrevista, media_feedback, media_infraestrutura, media_integracao, media_remuneracao, media_rotina, media_lideranca, media_geral, salario_min_piso, salario_max_teto, salario_base_medio, created_at) VALUES (15, 2.10, 2.50, 2.00, 1.80, 2.20, 3.00, 1.50, 2.50, 2.00, 2.80, 1.20, 1.50, 2.09, 1800.00, 3200.00, 2500.00, NOW());
INSERT INTO empresa_media (id, media_ambiente, media_aprendizado, media_beneficios, media_cultura, media_efetivacao, media_entrevista, media_feedback, media_infraestrutura, media_integracao, media_remuneracao, media_rotina, media_lideranca, media_geral, salario_min_piso, salario_max_teto, salario_base_medio, created_at) VALUES (16, 4.30, 4.60, 5.00, 4.20, 4.50, 4.10, 3.90, 4.90, 4.40, 4.80, 3.20, 4.10, 4.33, 4500.00, 10000.00, 7250.00, NOW());

-- 5. EMPRESAS
INSERT INTO empresa (id, uuid, nome_fantasia, cnpj, `user`, email, senha, id_empresa_media, biografia, pais_origem, receita_anual, data_fundacao, tamanho_empresa, estado_sede, media_salarial, area_atuacao, link_site, link_linkedin, link_gupy, created_at) VALUES (1, 'uuid-1', 'GFT Technologies', '12345678000199', 'gft', 'rh@gft.com', '123', 1, 'Líder em tecnologia.', 'Alemanha', 'R$500 milhões', '1987-03-01', '5001-10000', 'SP', 6000.00, 'Tecnologia', 'https://gft.com', 'li/gft', 'gupy/gft', NOW());
INSERT INTO empresa (id, uuid, nome_fantasia, cnpj, `user`, email, senha, id_empresa_media, biografia, pais_origem, receita_anual, data_fundacao, tamanho_empresa, estado_sede, media_salarial, area_atuacao, link_site, link_linkedin, link_gupy, created_at) VALUES (7, 'uuid-7', 'Unicórnio Global', '00000000000100', 'unicorn', 'jobs@unicorn.io', '123', 7, 'Melhor lugar do mundo.', 'EUA', 'R$500 milhões', '2010-01-01', '50001-100000', 'SP', 15000.00, 'Tecnologia', 'https://unicorn.io', 'li/unicorn', 'gupy/unicorn', NOW());
INSERT INTO empresa (id, uuid, nome_fantasia, cnpj, `user`, email, senha, id_empresa_media, biografia, pais_origem, receita_anual, data_fundacao, tamanho_empresa, estado_sede, media_salarial, area_atuacao, link_site, link_linkedin, link_gupy, created_at) VALUES (8, 'uuid-8', 'Fábrica de Software X', '99999999000199', 'fabrica_x', 'rh@fabricax.com', '123', 8, 'Apenas entregue o código.', 'Brasil', 'R$1 milhão', '2000-01-01', '501-1000', 'RJ', 2500.00, 'Tecnologia', 'https://fabricax.com', 'li/fabricax', 'gupy/fabricax', NOW());
INSERT INTO empresa (id, uuid, nome_fantasia, cnpj, `user`, email, senha, id_empresa_media, biografia, pais_origem, receita_anual, data_fundacao, tamanho_empresa, estado_sede, media_salarial, area_atuacao, link_site, link_linkedin, link_gupy, created_at) VALUES (11, 'uuid-11', 'Magazine Luiza', '11111111000111', 'magalu', 'talentos@magalu.com', '123', 11, 'Vem ser feliz.', 'Brasil', 'R$500 milhões', '1957-11-16', '10001-50000', 'SP', 4000.00, 'Varejo', 'https://magalu.com', 'li/magalu', 'gupy/magalu', NOW());
INSERT INTO empresa (id, uuid, nome_fantasia, cnpj, `user`, email, senha, id_empresa_media, biografia, pais_origem, receita_anual, data_fundacao, tamanho_empresa, estado_sede, media_salarial, area_atuacao, link_site, link_linkedin, link_gupy, created_at) VALUES (12, 'uuid-12', 'XP Inc', '22222222000122', 'xpinc', 'carreiras@xp.com', '123', 12, 'Transformando o mercado.', 'Brasil', 'R$500 milhões', '2001-05-04', '5001-10000', 'SP', 9000.00, 'Finanças', 'https://xpinc.com', 'li/xpinc', 'gupy/xpinc', NOW());
INSERT INTO empresa (id, uuid, nome_fantasia, cnpj, `user`, email, senha, id_empresa_media, biografia, pais_origem, receita_anual, data_fundacao, tamanho_empresa, estado_sede, media_salarial, area_atuacao, link_site, link_linkedin, link_gupy, created_at) VALUES (14, 'uuid-14', 'Flow State Tech', '44444444000144', 'flowstate', 'hi@flow.tech', '123', 14, 'Cultura em primeiro lugar.', 'Brasil', 'R$10 milhões', '2020-01-01', '101-500', 'SC', 5000.00, 'Tecnologia', 'https://flow.tech', 'li/flow', 'gupy/flow', NOW());
INSERT INTO empresa (id, uuid, nome_fantasia, cnpj, `user`, email, senha, id_empresa_media, biografia, pais_origem, receita_anual, data_fundacao, tamanho_empresa, estado_sede, media_salarial, area_atuacao, link_site, link_linkedin, link_gupy, created_at) VALUES (15, 'uuid-15', 'Old School Outsourcing', '55555555000155', 'oldschool', 'rh@oldschool.com', '123', 15, 'Tradição em entregas.', 'Brasil', 'R$50 milhões', '1995-01-01', '1001-5000', 'PR', 3000.00, 'Tecnologia', 'https://oldschool.com', 'li/oldschool', 'gupy/oldschool', NOW());
INSERT INTO empresa (id, uuid, nome_fantasia, cnpj, `user`, email, senha, id_empresa_media, biografia, pais_origem, receita_anual, data_fundacao, tamanho_empresa, estado_sede, media_salarial, area_atuacao, link_site, link_linkedin, link_gupy, created_at) VALUES (16, 'uuid-16', 'Itaú Unibanco', '60701190000104', 'itau', 'carreiras@itau.com.br', '123', 16, 'O maior banco privado do Brasil.', 'Brasil', 'R$500 milhões', '1924-12-30', '50001-100000', 'SP', 5500.00, 'Finanças', 'https://itau.com.br', 'li/itau', 'gupy/itau', NOW());

-- 6. AVALIAÇÕES (Setores baseados no seu DataLoader: 4=Financeiro, 8=TI, 2=Comercial)
INSERT INTO estudante_avaliacao (uuid, id_estudante, id_empresa, id_setor, estado_atuacao, modelo_trabalho, data_inicio, titulo_cargo, texto_avaliacao, salario_min, salario_max, anonima, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES ('aval-1', 1, 1, 8, 'SP', 'Híbrido', '2023-01-01', 'Estagiário Java', 'Entrei como estagiário e em 6 meses já estava contribuindo em projetos reais com Java e Spring Boot. A GFT tem uma cultura forte de aprendizado, com mentores dedicados. O modelo híbrido funciona bem, com 2 dias no escritório e 3 remotos. Único ponto negativo foi a demora no processo de recrutamento, que levou quase 2 meses.', 2500, 3000, false, 5, 5, 4, 5, 5, 4, 5, 5, 5, 4, 4, 5, NOW());
INSERT INTO estudante_avaliacao (uuid, id_estudante, id_empresa, id_setor, estado_atuacao, modelo_trabalho, data_inicio, titulo_cargo, texto_avaliacao, salario_min, salario_max, anonima, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES ('aval-2', 2, 8, 8, 'RJ', 'Presencial', '2023-01-10', 'Dev Junior', 'Infelizmente não foi uma boa experiência. Ambiente extremamente pressionado, com metas irreais e pouco suporte dos seniors. A empresa trata desenvolvedores como esteiras de código, sem qualquer preocupação com qualidade de vida. Rotatividade altíssima — em 3 meses vi pelo menos 5 pessoas saírem.', 2000, 2200, false, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, NOW());
INSERT INTO estudante_avaliacao (uuid, id_estudante, id_empresa, id_setor, estado_atuacao, modelo_trabalho, data_inicio, titulo_cargo, texto_avaliacao, salario_min, salario_max, anonima, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES ('aval-10', 5, 12, 4, 'SP', 'Híbrido', '2023-01-15', 'Analista Financeiro', 'Salário realmente muito acima do mercado para a posição, e os bônus são generosos. Porém, a cultura é extremamente competitiva e o ritmo é puxado. Se você aguenta pressão e entrega resultados, é um ótimo lugar para crescer financeiramente. Não recomendo para quem busca equilíbrio entre vida pessoal e profissional.', 7000, 9000, false, 3, 5, 5, 2, 4, 4, 3, 5, 3, 5, 1, 2, NOW());
INSERT INTO estudante_avaliacao (uuid, id_estudante, id_empresa, id_setor, estado_atuacao, modelo_trabalho, data_inicio, titulo_cargo, texto_avaliacao, salario_min, salario_max, anonima, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES ('aval-11', 6, 14, 8, 'SC', 'Remoto', '2023-03-01', 'UX Designer', 'Melhor cultura que já vi em uma empresa de tecnologia. Ambiente remoto bem estruturado, com comunicação assíncrona eficiente e workshops semanais de desenvolvimento pessoal. O salário não é o mais alto do mercado, mas os benefícios não financeiros (horários flexíveis, dias de saúde mental, plano de carreira claro) compensam muito.', 4500, 5000, false, 5, 5, 2, 5, 3, 5, 5, 3, 5, 2, 5, 5, NOW());
INSERT INTO estudante_avaliacao (uuid, id_estudante, id_empresa, id_setor, estado_atuacao, modelo_trabalho, data_inicio, titulo_cargo, texto_avaliacao, salario_min, salario_max, anonima, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES ('aval-12', 7, 15, 8, 'PR', 'Presencial', '2022-12-01', 'Suporte Técnico', 'Pressão constante e nenhum feedback construtivo dos gestores. O salário é baixo para a região e as condições de trabalho são precárias — cadeiras desconfortáveis, computadores lentos, sem plano de carreira. A única vantagem é que aprendi a me virar sozinho, já que não havia nenhum tipo de treinamento ou onboarding.', 2500, 2800, false, 2, 2, 2, 2, 2, 3, 1, 2, 2, 3, 1, 1, NOW());
INSERT INTO estudante_avaliacao (uuid, id_estudante, id_empresa, id_setor, estado_atuacao, modelo_trabalho, data_inicio, titulo_cargo, texto_avaliacao, salario_min, salario_max, anonima, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES ('aval-13', 2, 11, 2, 'SP', 'Híbrido', '2023-04-01', 'Estagiária Tech', 'Comecei como estagiária no Magalu e foi uma experiência transformadora. O programa de estágio é bem estruturado, com rotação entre áreas e mentoria de profissionais experientes. Ambiente acolhedor e diverso, com muitas mulheres em posições de liderança. Efetivação com aumento salarial significativo após 1 ano.', 2200, 2500, false, 4, 5, 4, 5, 4, 4, 4, 4, 5, 4, 4, 4, NOW());
INSERT INTO estudante_avaliacao (uuid, id_estudante, id_empresa, id_setor, estado_atuacao, modelo_trabalho, data_inicio, titulo_cargo, texto_avaliacao, salario_min, salario_max, anonima, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES ('aval-16', 1, 16, 4, 'SP', 'Híbrido', '2023-06-01', 'Dev Java Jr', 'Benefícios simplesmente impecáveis: plano de saúde top, previdência privada com contrapartida, participação nos lucros generosa, auxílio educação, gympass e muito mais. A estrutura do escritório é moderna e o home office funciona bem. Pontos de melhoria: processo burocrático para promoções e excesso de reuniões.', 5000, 6500, false, 4, 5, 5, 4, 5, 4, 4, 5, 4, 5, 3, 4, NOW());

-- 7. RELAÇÃO EMPRESA_SETOR
INSERT INTO empresa_setor (id_empresa, id_setor) VALUES (1, 8);
INSERT INTO empresa_setor (id_empresa, id_setor) VALUES (11, 2);
INSERT INTO empresa_setor (id_empresa, id_setor) VALUES (11, 8);
INSERT INTO empresa_setor (id_empresa, id_setor) VALUES (12, 4);
INSERT INTO empresa_setor (id_empresa, id_setor) VALUES (14, 8);
INSERT INTO empresa_setor (id_empresa, id_setor) VALUES (16, 4);
INSERT INTO empresa_setor (id_empresa, id_setor) VALUES (16, 8);

-- 8. AVALIAÇÕES ANÔNIMAS
INSERT INTO estudante_avaliacao (uuid, id_estudante, id_empresa, id_setor, estado_atuacao, modelo_trabalho, data_inicio, titulo_cargo, texto_avaliacao, salario_min, salario_max, anonima, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES ('aval-20', 5, 1, 8, 'SP', 'Híbrido', '2023-02-01', 'Dev Pleno', 'Vou manter anônimo porque ainda trabalho na área e não quero me expor. No geral é uma boa empresa, com benefícios razoáveis e clima tranquilo. Mas o processo seletivo é extremamente demorado — fiz 5 etapas ao longo de 3 meses. A comunicação entre RH e gestão é confusa, e tive que correr atrás de retorno várias vezes.', 4000, 5500, true, 4, 4, 4, 4, 3, 3, 4, 4, 4, 4, 4, 4, NOW());
INSERT INTO estudante_avaliacao (uuid, id_estudante, id_empresa, id_setor, estado_atuacao, modelo_trabalho, data_inicio, titulo_cargo, texto_avaliacao, salario_min, salario_max, anonima, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES ('aval-21', 6, 16, 4, 'SP', 'Remoto', '2023-06-01', 'Analista Financeiro', 'Banco sólido com benefícios excelentes, especialmente a previdência privada e o plano de saúde que cobre dependentes sem coparticipação. Por outro lado, o ritmo é intenso e a burocracia interna desgasta. Muitos processos manuais que poderiam ser automatizados. Se você valoriza estabilidade e benefícios, compensa. Se busca inovação e agilidade, talvez não seja o melhor lugar.', 5000, 7000, true, 4, 4, 5, 3, 4, 4, 3, 5, 4, 5, 3, 4, NOW());

-- 9. COMENTÁRIOS DOS ESTUDANTES
INSERT INTO estudante_avaliacao_coment (uuid, id_estudante, id_avaliacao, texto, anonima, created_at) VALUES ('coment-1', 2, 1, 'Fiz estágio lá no ano passado e confirmo cada ponto da avaliação. O time de Java é muito bom, aprendi demais com os seniors. Só adiciono que a GFT investe bastante em certificações — tirei a AWS Cloud Practitioner pagando por eles.', false, NOW());
INSERT INTO estudante_avaliacao_coment (uuid, id_estudante, id_avaliacao, texto, anonima, created_at) VALUES ('coment-2', 5, 1, 'Acho que depende muito do projeto e do gestor. No meu caso, tive uma experiência bem diferente — meu líder era ausente e o projeto estagnado. A avaliação original parece refletir bem um cenário positivo, mas nem todo mundo tem essa sorte.', true, NOW());
INSERT INTO estudante_avaliacao_coment (uuid, id_estudante, id_avaliacao, texto, anonima, created_at) VALUES ('coment-3', 6, 2, 'Tive exatamente a mesma experiência. Fiquei 4 meses e saí. Ambiente tóxico, gestor que nunca dava feedback e ainda cobrava horas extras não remuneradas. Fuja dessa empresa se puder.', false, NOW());
INSERT INTO estudante_avaliacao_coment (uuid, id_estudante, id_avaliacao, texto, anonima, created_at) VALUES ('coment-4', 7, 10, 'Salário realmente é o grande atrativo da XP, mas a avaliação foi justa ao apontar o ritmo intenso. Conheço gente que adora a competição saudável de lá, e gente que pediu as contas em 6 meses porque não aguentou a pressão.', true, NOW());
INSERT INTO estudante_avaliacao_coment (uuid, id_estudante, id_avaliacao, texto, anonima, created_at) VALUES ('coment-5', 1, 13, 'Magalu foi meu primeiro emprego e sou grata até hoje. A cultura de inclusão é genuína — participei de grupos de afinidade e me senti acolhida desde o primeiro dia. O programa de estágio é referência, recomendo de olhos fechados.', false, NOW());

-- 10. RESPOSTAS DAS EMPRESAS
INSERT INTO empresa_avaliacao_coment (uuid, id_empresa, id_avaliacao, texto, created_at) VALUES ('emp-coment-1', 1, 1, 'Agradecemos o feedback detalhado! Ficamos felizes que sua experiência como estagiário foi positiva. Sabemos que nosso processo seletivo pode ser demorado e estamos trabalhando para reduzi-lo. Seus apontamentos sobre os mentores e as certificações nos motivam a continuar investindo em nossos programas de desenvolvimento.', NOW());
INSERT INTO empresa_avaliacao_coment (uuid, id_empresa, id_avaliacao, texto, created_at) VALUES ('emp-coment-2', 8, 2, 'Lamentamos profundamente sua experiência. Estamos passando por uma reestruturação interna para melhorar a qualidade de vida dos nossos colaboradores. Já implementamos um novo programa de onboarding e contratamos novos líderes técnicos. Esperamos que, em uma futura oportunidade, possamos oferecer uma experiência diferente.', NOW());
INSERT INTO empresa_avaliacao_coment (uuid, id_empresa, id_avaliacao, texto, created_at) VALUES ('emp-coment-3', 16, 16, 'Que bom que nossos benefícios fizeram diferença na sua trajetória! Trabalhamos constantemente para oferecer o melhor pacote do mercado. Quanto ao ponto sobre a burocracia para promoções, estamos revisando nosso processo de carreira para torná-lo mais transparente e ágil. Obrigado pela contribuição!', NOW());

-- 11. NOTAS CONDICIONAIS DOS ESTUDANTES
INSERT INTO estudante_nota_condi (id_estudante, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES (1, 9, 10, 7, 9, 8, 5, 7, 8, 6, 8, 6, 9, NOW());
INSERT INTO estudante_nota_condi (id_estudante, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES (2, 10, 9, 8, 9, 7, 5, 8, 7, 8, 6, 5, 8, NOW());
INSERT INTO estudante_nota_condi (id_estudante, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES (5, 8, 9, 6, 7, 8, 6, 5, 9, 7, 9, 7, 8, NOW());
INSERT INTO estudante_nota_condi (id_estudante, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES (6, 9, 8, 9, 9, 6, 7, 8, 7, 8, 7, 6, 7, NOW());
INSERT INTO estudante_nota_condi (id_estudante, ambiente, aprendizado, beneficios, cultura, efetivacao, entrevista, feedback, infraestrutura, integracao, remuneracao, rotina, lideranca, created_at) VALUES (7, 7, 10, 5, 6, 9, 8, 6, 8, 9, 5, 4, 6, NOW());